config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :authors, controllers: {
    confirmation: 'confirmation'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  resources :authors, only: %i[index show] do
    resources :posts, only: %i[index show new create]
  end

  get '/posts/:id/newcomment', to: 'comments#new_comment'
  post '/addcomment/:id', to: 'comments#add_comment'
  post '/addlike/:id', to: 'likes#add_like'
  root 'authors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    Post.limit(3).order(created_at: :desc).where(author: self)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id'
  belongs_to :post
  after_save :update_comment_counter

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id'
  belongs_to :post
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id'
  has_many :comments
  has_many :likes
  after_save :update_post_counter
  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    Comment.limit(5).order(created_at: :desc).where(post: self)
  end

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/controllers/Author/confirmations_controller.rb
module Author
  class ConfirmationsController < Devise::ConfirmationsController
    private

    def after_confirmation_path_for(_resource_name, resource)
      sign_in(resource)
      new_author_session_path
    end
  end
end

app/controllers/Author/omniauth_callbacks_controller.rb
module Author
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  end
end

app/controllers/Author/passwords_controller.rb
module Author
  class PasswordsController < Devise::PasswordsController
  end
end

app/controllers/Author/registrations_controller.rb
module Author
  class RegistrationsController < Devise::RegistrationsController
  end
end

app/controllers/Author/sessions_controller.rb
module Author
  class SessionsController < Devise::SessionsController
  end
end

app/controllers/Author/unlocks_controller.rb
module Author
  class UnlocksController < Devise::UnlocksController
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def logging_out; end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!

  def show
    @author = Author.find(params[:id])
  end

  def index
    @authors = Author.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new_comment
    @id = current_author.id
    @post = Post.find(params[:id])
  end

  def add_comment
    @commented_post = Post.find(params[:id])
    comment = Comment.new(text: params[:text], author: current_author, post: @commented_post)
    if comment.save
      flash[:success] = 'success'
    else
      flash[:danger] = 'Error'
    end
    redirect_to "/authors/#{@commented_post.author_id}/posts/#{params[:id]}"
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def add_like
    @liked_post = Post.find(params[:id])
    like = Like.new(post: @liked_post, author: current_author)
    if Like.exists?(author: current_author, post: @liked_post)
      like.destroy
    else
      like.save
      redirect_to "/authors/#{@liked_post.author_id}/posts"
    end
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
    def index; end

    def show; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @author = Author.find(params[:author_id])
    @posts = @author.posts.includes(:comments)
  end

  def show
    @author = Author.find(params[:author_id])
    @post = @author.posts.find(params[:id])
  end

  def new
    @id = current_user.id
    @new_post = Post.new
  end

  def create
    post = Post.new(title: params[:title], text: params[:text], author: current_author)
    if post.save
      flash[:notice] = 'success'
      redirect_to "/authors/#{current_author.id}/posts"
    else
      flash[:error] = 'Error'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/index.html.erb
<div class="page_container">
  <% @authors.each do |a| %>
  <div class="author_container">
    <div class="image_placeholder">
      <img src=<%= a.photo%> alt="" >
    </div>
    <div class="details">
      <h1>
        <a href='/authors/<%= a.id %>' class="author_link">
        <%= a.name %>
      </a>
      </h1>
      <p>Number of posts: <%= a.posts_counter %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/authors/show.html.erb
<div class="page_container">
  <div class="author_container">
    <div class="image_placeholder">
      <img src=<%= @author.photo%> alt="" >
    </div>
    <div class="details">
      <h1><%= @author.name %></h1>
      <p>Number of posts: <%= @author.posts_counter %></p>
    </div>
  </div>
  <div class="bio">
    <%= @author.bio %>
  </div>
  <% @author.most_recent_posts.each do |a| %>
  <div class="posts">
    <h4>
      <a class="single_post" href="/authors/<%= @author.id %>/posts/<%= a.id %>">
        Post #<%= (@author.posts.find_index(a) + 1)  %>
      </a>
    </h4>
    <p><%= a.text %></p>
    <div class="stats">
      <p>Comments: <%= a.comments_counter %>,</p>
      <p>Likes: <%= a.likes_counter %></p>
    </div>
  </div>
  <% end %>
  <button class="button">
    <a class="link" href='/authors/<%= @author.id %>/posts'>
    See All Posts
    </a>
  </button>
</div>

app/views/comments/new_comment.html.erb
<%=form_with url: "/addcomment/#{@post.id}" do |form| %>
  <%= form.text_field(:text) %>
  <%= form.submit("Add Comment") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p> <p class="alert"><%= alert %></p> <ul> <% if author_signed_in? %> <li><%= link_to "Hi, #{current_author.name}", edit_author_registration_path %></li> <li><%= button_to "logout", destroy_author_session_path(current_author), method: :delete %></li> <% else %> <li><%= link_to 'Sign In', new_author_session_path %></li> <li><%= link_to 'Sign Up', new_author_registration_path %></li> <% end %> </ul> 

    <%= yield %>
  </body>
</html>

app/views/layouts/users/index.show.erb
<h2>Here is a list of all selected Users</h2>

app/views/posts/index.html.erb
<div class="page_container">
  <%= button_to "logout", destroy_author_session_path, method: :delete  %>
  <div class="author_container">
    <div class="image_placeholder">
      <img src=<%= @author.photo%> alt="" >
    </div>
    <div class="details">
      <h1><%= @author.name %></h1>
      <p>Number of posts: <%= @author.posts_counter %></p>
    </div>
  </div>

  <%= form_with model: @new_post, url: author_posts_url, html: {class: "add_post_form"} do |form| %>
    <%= form.label(:title, "Title:") %>
    <%= form.text_field(:title) %>
    <%= form.label(:text, "Text:") %>
    <%= form.text_field(:text) %>
    <%= form.submit("Create Post") %>
  <% end %>

  <% @posts.each do |a| %>
  <div class="posts">
    <a class="link" href='/authors/<%= @author.id %>/posts/<%= a.id%>'>
      <h4>Post #<%= (@author.posts.find_index(a) + 1)%>: <%= a.title  %></h4>
    </a>
    <p><%= a.text %></p>
    <div class="stats">
      <%= form_with url: "/addlike/#{a.id}" do |form| %>
        <%= form.submit("Add Like") %>
      <% end %>
      <p>Comments: <%= a.comments_counter %>,</p>
      <p>Likes: <%= a.likes_counter %></p>
    </div>
  </div>
  <% if a.recent_comments.empty? %>
  <% else %>
    <div class="comments">
      <% a.recent_comments.each do |comment| %>
        <p class="comment_texts"><%= Author.find(comment.author_id).name%>: <%= comment.text%> </p>
      <% end %>
    </div>
  <% end %>
  <% end %>
  <button class="button">Pagination</button>
</div>

app/views/posts/show.html.erb
<div class="page_container">
  <div class="full_post">
    <div class="header">
      <p class="header_info">Post #<%= @author.posts.find_index(@post) + 1%> by <%= @post.author.name %></p>
      <h3><%= @post.title %></h3>
      <p class="header_comments">Comments: <%= @post.comments_counter %>,</p>
      <p class="header_likes">Likes: <%= @post.likes_counter %></p>
    </div>
    <p><%= @post.text %></p>
  </div>

  <div class="all_comments">
    <button>
      <a href="/posts/<%= @post.id%>/newcomment">Add Comment</a>
    </button>
    <% @post.comments.each do |c| %>
      <td><%= c.author.name %>:</td>
      <td><%= c.text %></td>
      <br />
    <% end %>
  </div>
</div>